language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=django==1.4
  - DJANGO=https://www.djangoproject.com/download/1.5c2/tarball/

install:
  - pip install psycopg2
  - pip install $DJANGO

script: python setup.py test

before_script:
  - psql -c 'create database django_nopassword;' -U postgres
